[package]
name = "crawler"
version = "0.1.0"
authors = ["Bruce Li <leilmyxwz@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
rocket = "*"
rocket_codegen = "*"
select = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
threadpool = "1.0"
